const path = `./`;
const assets = `${path}/assets`;
export const pwgenIcon = `${assets}/pwgen.png`;
export const autocompleteIcon = `${assets}/autocomplete.png`;
export const braveIcon = `${assets}/brave.png`;
export const grafanaIcon = `${assets}/grafana.png`;
export const kibanaIcon = `${assets}/kibana.png`;
export const cmdIcon = `${assets}/cmd.png`;
export const timeIcon = `${assets}/time.png`;
